version: "3.9"

services:
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    # TODO add pass in config
    # --requirepass secret123
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes: 
      - cache:/data
  
  bf-protector:
    build:
      context: ../.
      dockerfile: ./Dockerfile
    image: bf-protector:develop
    container_name: bf-protector-app
    environment:
      STORAGE_SOURCE: "cache:6379"
      GRPCSERVER_HOST: "bf-protector-app"
      # STORAGE_PASSWORD: "secret123"
    ports:
      - "8081:8081"
    depends_on:
      cache:
        condition: service_healthy
    command: ./app/bf-protector -config=/config/config.toml
    restart: on-failure

volumes:
  cache:
    driver: local