[GRPCSERVER]
host = "localhost"
port = ":8081"
network = "tcp"

[STORAGE]
source = "localhost:6379"
password="secret123"

[ATTEMPTSLIMIT]
loginRequestsMinute = 10
passwordRequestsMinute = 100
ipRequestsMinute = 1000