name: Go test and build pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Build
        run: go build -v ./...

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./internal/...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          linters-settings:
            funlen:
              lines: 150
              statements: 80

          linters:
            disable-all: true
            enable:
              - asciicheck
              - bodyclose
              - deadcode
              - depguard
              - dogsled
              - dupl
              - durationcheck
              - errorlint
              - exhaustive
              - exportloopref
              - funlen
              - gci
              - gocognit
              - goconst
              - gocritic
              - gocyclo
              - godot
              - gofmt
              - gofumpt
              - goheader
              - gomoddirectives
              - gomodguard
              - goprintffuncname
              - gosec
              - gosimple
              - govet
              - ifshort
              - importas
              - ineffassign
              - lll
              - makezero
              - misspell
              - nestif
              - nilerr
              - noctx
              - nolintlint
              - prealloc
              - predeclared
              - revive
              - rowserrcheck
              - sqlclosecheck
              - staticcheck
              - structcheck
              - stylecheck
              - tagliatelle
              - thelper
              - tparallel
              - typecheck
              - unconvert
              - unparam
              - unused
              - varcheck
              - wastedassign
              - whitespace