name: Go test and build pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'

    - name: Build
      run: go build -v ./...

    - name: Unit tests
      run: go test -v -count=1 -race -timeout=1m ./...
